name: "Tele-VPS : Initialize"

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: "🛃 Checkout Tele-Linux 🛃"
         uses: actions/checkout@main
       
       - name: "⛔️ Cancel Duplicate Runs ⛔️"
         uses: styfle/cancel-workflow-action@0.9.0
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: "📈 Initialize Tele-Linux 📉"
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: "🧬 Clone Repository 🧬"
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} telerepo
       - name: "Running Tele-VPS Server 🏃‍♂️💨💨"
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd telerepo
           docker build . -t tele-vps
           docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} tele-vps
       - name: "♻️ Re-Run Tele-VPS Server ♻️"
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Tele-VPS : Re-Run $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:Tele-VPS
